version: "3"

services:
  auth-server-efcore:
    build:
      context: src/AuthServerSamples
      dockerfile: AuthServerEfCore.Web/Dockerfile
    depends_on:
      - database
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
  database:
    image: postgres:13.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - database:/var/lib/postgresql/data

  migrator:
    depends_on:
      - database
    build:
      context: ./src/AuthServerSamples
      dockerfile: ./AuthServer.EfCoreMigrator/Dockerfile
    command:
      -- -e Docker
volumes:
  database: