version: "3"

services:
  auth-server-efcore:
    build:
      context: src/AuthServerSamples
      dockerfile: AuthServerEfCore.Web/Dockerfile
    depends_on:
      - user-db
      - configuration-db
      - persisted-grant-db
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  user-db:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - user-db:/var/lib/postgresql/data

  configuration-db:
    image: postgres:13.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - configuration-db:/var/lib/postgresql/data
      
  persisted-grant-db:
    image: postgres:13.1
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - persisted-grant-db:/var/lib/postgresql/data
volumes:
  user-db:
  configuration-db:
  persisted-grant-db: