#-------------------------------------------------------------------------------
FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /src
COPY . .
WORKDIR /src/AuthServer.EfCoreMigrator
ENTRYPOINT ["dotnet", "run"]